FROM jenkins/jenkins:lts

# Переключаемся на пользователя root, чтобы установить пакеты
USER root

# Обновляем пакеты и устанавливаем Docker CLI
RUN apt-get update && apt-get install -y docker.io

# Добавляем пользователя jenkins в группу docker
RUN usermod -aG docker jenkins

# Возвращаемся к пользователю jenkins
USER jenkins
